node {
  stage('SCM') {
    checkout scm
  }

  stage('Build and SonarQube Analysis') {
    def mvn = tool 'Default Maven'
    withSonarQubeEnv() {
      // Compile the Java code using Maven
      sh "${mvn}/bin/mvn clean install"

      // Run SonarQube analysis
      sh "${mvn}/bin/mvn sonar:sonar -Dsonar.projectKey=WhiskerWelfare -Dsonar.projectName='WhiskerWelfare'"
    }
  }
}
